create table modalidade_evento
(
    id          integer generated always as identity
        constraint modalidade_evento_pk
            primary key,
    descricao   varchar not null,
    data_inc    timestamp,
    usuario_inc varchar
);

comment on column modalidade_evento.id is 'Identificador de modalidade de evento';

comment on column modalidade_evento.descricao is 'Descrição da modalidade do evento';

alter table modalidade_evento
    owner to admin;

create table usuario
(
    id_usuario           integer generated by default as identity
        constraint pk_usuario
            primary key,
    nome                 varchar(50)                             not null,
    email                varchar(100)                            not null
        constraint unq_usuario_email
            unique,
    login                varchar(100)                            not null
        constraint unq_usuario_login
            unique,
    senha                varchar(200)                            not null,
    telefone             varchar(11),
    telefone_whatsapp    varchar(11),
    ativo                boolean                                 not null,
    id_usuario_inclusao  integer                                 not null,
    id_usuario_alteracao integer                                 not null,
    data_inclusao        timestamp default statement_timestamp() not null,
    data_alteracao       timestamp default statement_timestamp() not null
);

alter table usuario
    owner to admin;

create table tipo_evento
(
    id        integer generated always as identity
        constraint tipo_evento_pk
            primary key,
    descricao varchar
);

alter table tipo_evento
    owner to admin;

create table organizacao
(
    id               integer generated always as identity
        constraint id_pk
            primary key,
    cnpj             varchar not null
        constraint organizacao_pk
            unique,
    nome_organizacao varchar,
    data_inc         timestamp,
    usuario_inc      varchar
);

comment on table organizacao is 'Tabela responsavel por armazenar informações de organizadores';

alter table organizacao
    owner to admin;

create table eventos
(
    id                integer generated always as identity
        constraint eventos_pk
            primary key,
    nome              varchar,
    data_evento       timestamp,
    cidade            varchar,
    estado            varchar,
    pais              varchar,
    id_tipo           integer
        constraint fk_tipo
            references tipo_evento,
    id_modalidade     integer not null
        constraint fk_modalidade
            references modalidade_evento,
    data_inclusao     timestamp,
    data_alteracao    timestamp,
    usuario_inclusao  varchar,
    usuario_alteracao varchar,
    id_organizacao    integer
        constraint fk_organizacao
            references organizacao,
    imagem_evento     varchar,
    inscricao_aberta  boolean,
    distancia         varchar,
    vagas             integer,
    vagas_disponiveis integer
);

comment on table eventos is 'Tabela destinada a armazenar os eventos esportivos';

alter table eventos
    owner to admin;

create table time
(
    id        integer not null
        constraint id_time_pk
            primary key,
    nome_time varchar not null
);

alter table time
    owner to admin;

create table usuario_time
(
    id_usuario integer
        constraint id_usuario_time_fk
            references usuario,
    id_time    integer
        constraint id_time_usuario_fk
            references time
);

alter table usuario_time
    owner to admin;

create table eventos_usuario
(
    id_eventos integer
        constraint events_usuario_fk
            references eventos,
    id_usuario integer
        constraint usuario_eventos_fk
            references usuario
);

alter table eventos_usuario
    owner to admin;

